import argparse
import os
from pathlib import Path, PurePath
import subprocess
from subprocess import PIPE

from misc_utils.logging_utils import create_logger


logger = create_logger(__name__, 'sh', 'INFO')

# Params
wbt = 'whitebox_tools'
med = 'MaxElevationDeviation'


def run_subprocess(command):
    proc = subprocess.Popen(command, stdout=PIPE, stderr=PIPE, shell=True)
    # proc.wait()
    output, error = proc.communicate()
    logger.debug('Output: {}'.format(output.decode()))
    logger.debug('Err: {}'.format(error.decode()))


def wbt_med(dem, out_dir=None, out_mag=None, out_scale=None,
            min_scale=1, max_scale=50, step=5, vw=False,
            dryrun=False):
    logger.info('Setting up whitebox_tool.exe MaxElevationDeviation')
    if not isinstance(dem, PurePath):
        dem = Path(dem)
    if not isinstance(out_dir, PurePath):
        out_dir = Path(out_dir)
    if not out_mag:
        out_mag = out_dir / '{}_med_mag_{}-{}-{}{}'.format(dem.stem, min_scale,
                                                           max_scale, step, dem.suffix)
    if not out_scale:
        out_scale = out_dir / '{}_med_scl_{}-{}-{}{}'.format(dem.stem, min_scale,
                                                             max_scale, step, dem.suffix)

    logger.info("""
    DEM: {}
    Magnitude: {}
    Scale: {}
    Min_scale: {}
    Max_scale: {}
    Step: {}
    """.format(dem, out_mag, out_scale, min_scale, max_scale, step))

    # Create command string
    cmd = "{} -r={} --dem={} --out_mag={} --out_scale={} " \
          "--min_scale={} --max_scale={} --step={}""".format(wbt, med, dem, out_mag, out_scale,
                                                             min_scale, max_scale, step)
    if vw:
        cmd += ' -v'

    if not dryrun:
        logger.info('Running MaxElevationDeviation...')
        logger.debug(cmd)
        run_subprocess(cmd)

    logger.info('Done')

    return out_mag


if __name__ == '__main__':
    parser = argparse.ArgumentParser('Wrapper for Whitebox Tools MaxElevationDeviation tool, with'
                                     'automatically generated output names based on input parameters.')
    parser.add_argument('-i', '--dem', type=os.path.abspath,
                        help='Path to DEM to process.')
    parser.add_argument('-od', '--out_dir', type=os.path.abspath,
                        help='Directory to write output files to, name will be autogenerated'
                             'from input parameters: '
                             '[dem name]_med_[out file type]_[min]-[max]-[step]')
    parser.add_argument('--out_mag', type=os.path.abspath,
                        help='Path to write magnitude file to.')
    parser.add_argument('--out_scale', type=os.path.abspath,
                        help='Path to write scale file to.')
    parser.add_argument('--min_scale', type=int,
                        help='Minimum search neighbourhood radius in grid cells.')
    parser.add_argument('--max_scale', type=int,
                        help='Maximum search neighbourhood radius in grid cells.')
    parser.add_argument('--step', type=int,
                        help='Step size as any positive non-zero integer.')
    parser.add_argument('--dryrun', action='store_true',
                        help='Print actions without performing.')
    parser.add_argument('-vw', '--verbose_wbt', action='store_true',
                        help='Run tool with verbose flag.')
    parser.add_argument('-v', '--verbose', action='store_true',
                        help='Set logging to DEBUG.')

    args = parser.parse_args()

    dem = Path(args.dem)
    out_mag = args.out_mag
    out_scale = args.out_scale
    min_scale = args.min_scale
    max_scale = args.max_scale
    step = args.step

    if args.verbose:
        log_lvl = 'DEBUG'
    else:
        log_lvl = 'INFO'
    logger = create_logger(__name__, 'sh', log_lvl)


    # Determine out_dir if not provided
    if not args.out_dir:
        out_dir = dem.parent
    else:
        out_dir = Path(args.out_dir)

    # Create log file
    log_file = out_dir / '{}_mdfm_{}-{}-{}.log'.format(dem.stem, min_scale,
                                                       max_scale, step)
    logger = create_logger(__name__, 'fh', 'DEBUG',
                           filename=log_file)

    # Run
    wbt_med(dem=dem, out_dir=out_dir,
            out_mag=out_mag, out_scale=out_scale,
            min_scale=min_scale, max_scale=max_scale,
            step=step, vw=args.verbose_wbt,
            dryrun=args.dryrun)
