---
project:
  EPSG: 3413
  OUT_VEC_FMT: ".shp"
  AOI: E:\disbr007\umn\2020sep27_eureka\aois\test_aoi.shp
pansharpen:
  t: UInt16
  c: mr
dem_deriv:
  med:
    min_scale: 1
    max_scale: 25
    step: 1
  curv:
    curv_type: ProfileCurvature
headwall:
  seg:
    algorithm: grm
    params:
      criterion: bs
      threshold: 100
      niter: 0
      speed: 1
      spectral: 0.3
      spatial: 250
  cleanup:
    cleanup: 1
    params:
      mask_on: E:\disbr007\umn\2020sep27_eureka\dems\sel\WV02_20140703_1030010033A84300_1030010032B54F00_test_aoi\WV02_20140703_1030010033A84300_1030010032B54F00_2m_lsf_seg1_dem_masked_test_aoi.tif
      min_size: 0.5
      overwrite: true
  zonal_stats:
    params:
      rasters:
      - E:\disbr007\umn\2020sep27_eureka\config\zonal_stats.json
    stats:
    - mean
  classification:
    headwall_class_out: 1
    headwall_class_out_centroid: 1
rts:
  seg:
    algorithm: grm
    params:
      criterion: bs
      threshold: 750
      niter: 0
      speed: 0
      spectral: 0.6
      spatial: 100
  cleanup:
    cleanup: 1
    params:
      mask_on: E:\disbr007\umn\2020sep27_eureka\dems\sel\WV02_20140703_1030010033A84300_1030010032B54F00_test_aoi\WV02_20140703_1030010033A84300_1030010032B54F00_2m_lsf_seg1_dem_masked_test_aoi.tif
      min_size: 0.5
      overwrite: true
  zonal_stats:
    params:
      rasters:
      - E:\disbr007\umn\2020sep27_eureka\config\zonal_stats.json
    stats:
    - mean
  classification:
    rts_class_out: 1
