# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# arcpy_merge_MB.py
# Created on: 2019-08-22 06:31:38.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
gdb = r'C:\Users\disbr007\projects\coastline\coastline.gdb'
arcpy.env.workspace = gdb
mfp = 'mfp_subset'
nasa = 'nasa_subset'
oh_final_candidates = 'oh_subset'

for src in [mfp, nasa]:
    arcpy.AddField_management(src, 'src', field_type='TEXT')

# Process: Merge
arcpy.Merge_management([mfp, nasa],
                       oh_final_candidates,
                       '')

arcpy.DeleteIdentical_management(oh_final_candidates, "scene_id")
