# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# arcpy_connect_sdeMB.py
# Created on: 2019-08-16 16:12:56.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Set the necessary product code
#import arceditor


# Import arcpy module
import arcpy
import os

def danco_footprint_connection(layer):
    arcpy.env.overwriteOutput = True
    # Local variables:
    arcpy_cxn = "C:\\dbconn\\arcpy_cxn"
    #arcpy_footprint_MB_sde = arcpy_cxn
    
    # Process: Create Database Connection
    cxn = arcpy.CreateDatabaseConnection_management(arcpy_cxn, 
                                                     "footprint_arcpy.sde", 
                                                     "POSTGRESQL", 
                                                     "danco.pgc.umn.edu", 
                                                     "DATABASE_AUTH", 
                                                     "disbr007", 
                                                     "ArsenalFC10", 
                                                     "SAVE_USERNAME", 
                                                     "footprint", 
                                                     "", 
                                                     "TRANSACTIONAL", 
                                                     "sde.DEFAULT", 
                                                     "")
    
    arcpy.env.workspace = os.path.join("C:\\dbconn\\arcpy_cxn", "footprint_arcpy.sde")
    
#    featClasses = arcpy.ListFeatureClasses()
#    tables = arcpy.ListTables()
#    for fc in featClasses:
#        print(fc)
#    print('\n')
#    for tbl in tables:
#        print(tbl)
    
#    fc = arcpy.MakeFeatureLayer_management('footprint.sde.index_dg', 'in_memory\test')
    
#    return cxn, 'footprint.sde.index_dg'
    return '{}.sde.{}'.format('footprint', layer)

arcpy.env.overwriteOutput = True
arcpy.env.workspace = os.path.join("C:\\dbconn\\arcpy_cxn", "footprint_arcpy.sde")
fc_p = danco_footprint_connection('index_dg')

fc = arcpy.MakeFeatureLayer_management(fc_p, 'in_memory\test')